language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
after_success:
  - "mvn clean"
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "mvn deploy -Dmaven.test.skip=true --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
    - secure: "OJDLcOwQfo0OFzA9M/4se/a+7rAy/LruQbfmyQtblwCSAwaMPGCkmJl0YrjGixkwP8LCA5AlN1+8Gp3xDHnsh2yw7HgGBwS250e7JUvMCely0/8BM3PSIH0ZAcURPpBhU6xzRX+KJjN/GX8HhmaITRleHj9hjswZIc9oT0ZOgHI="
    - secure: "HxsG/72sYJ/E7mQVF9bx7DVfI+O7Ek/8mmJcmlUqxVgDynS48GIz1Qm63rFmR+lfj7SMfVCgDD0tlsjrIW+3FKEw7EZhPuNJ5shttDpS0h/r92OOSeqvH7nXT9aSEA8PVXc3Nza6I2p5olhI8zlHMj9AI3cjUlcGwZr+lDcfgQE="

services: redis-server
